[doc.extern-map.registries]
crates-io = "https://docs.rs/"

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native", "-C", "strip=symbols"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=native", "-C", "strip=symbols"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "strip=symbols"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "strip=symbols"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "strip=symbols"]